import { writeFileSync, mkdirSync } from 'fs';
import { join } from 'path';
import { NativeVerifyResult } from './openspec.js';
import { PlaywrightVerifyResult } from './playwright-agent.js';

export function generateReport(
  change: string,
  nativeResult: NativeVerifyResult,
  playwrightResult: PlaywrightVerifyResult,
  projectRoot: string
): string {
  const reportsDir = join(projectRoot, 'openspec', 'reports');
  mkdirSync(reportsDir, { recursive: true });

  const reportPath = join(reportsDir, `playwright-verify-${Date.now()}.md`);

  const failedTests = playwrightResult.tests.filter((t) => !t.passed);
  const passedTests = playwrightResult.tests.filter((t) => t.passed);

  const report = `# Playwright Verify Report

**Change:** ${change}
**Timestamp:** ${new Date().toISOString()}

## OpenSpec Native Verify

| Check | Status |
|-------|--------|
| Native verify | ${nativeResult.passed ? '✅ PASS' : '⚠ PARTIAL/FAIL'} |

${nativeResult.issues.length > 0 ? `### Issues\n${nativeResult.issues.map((i) => `- ${i}`).join('\n')}\n` : ''}

## Playwright E2E Verify

| Check | Status |
|-------|--------|
| Playwright E2E | ${playwrightResult.passed ? '✅ PASS' : '❌ FAIL'} |
| Total tests | ${playwrightResult.tests.length} |
| Passed | ${passedTests.length} |
| Failed | ${failedTests.length} |
| Attempts | ${playwrightResult.attempts} |

${failedTests.length > 0 ? `### Failed Tests\n${failedTests.map((t) => `- **${t.name}**: ${t.failure || 'Unknown error'}`).join('\n')}\n` : ''}

## Combined Result

**Overall:** ${nativeResult.passed && playwrightResult.passed ? '✅ ALL PASS' : '❌ SOME FAILURES'}

${!nativeResult.passed ? '- OpenSpec native verify had issues\n' : ''}${!playwrightResult.passed ? '- Playwright E2E verify failed\n' : ''}
---
*Generated by openspec-playwright*
`;

  writeFileSync(reportPath, report);
  return reportPath;
}
