name: Unpublish

on:
  workflow_dispatch:

jobs:
  unpublish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - run: npm deprecate openspec-playwright@0.1.67 "Use 0.1.66 instead. This version contains unintended changes."
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
